const jCategory = [
   { 
     index: 0,
     image: "../images/google.png",
     title: "Web Developer",
     rate:  "₹15000-40000/m",
     av: "Full Time",
     companyName: "Google",
     location: "India",
     vacancy: "02",
     hours: "50h / week",
     description: "Finergy division within Oracle FSGIU exclusively focuses on the Banking, Financial Services, and Insurance (BFSI) sector, offering deep domain knowledge to address complex financial needs. Finergy has Industry expertise in BFSI. (On Accelerated Implementation) Finergy has Proven methodologies that fast-track the deployment of multi-channel delivery platforms, minimizing IT intervention and reducing time to market. Due to Personalization tools that tailor customer experiences, Finergy has several loyal customers for over a decade. (On End-to-End Banking Solutions) Finergy Provides a single platform for a wide range of banking services—trade, treasury, cash management—enhancing operational efficiency with integrated dashboards and analytics. Finergy offers Expert Consulting Services, Comprehensive consulting support, from strategy development to solution implementation, ensuring the alignment of technology with business goals.",
     workplace: "Work from home",
     education: "Bachelor degree in any computer course",
     experience: "2 to 5 years",
    },
    { 
     index: 1,
     image: "../images/uber.png",
     title: "Freelancer",
     rate:  "₹9000-12000/Project",
     av: "Freelancer",
     companyName: "Uber",
     location: "India",
     vacancy: "01",
     hours: "25h / week",
     description: "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters,as opposed to using 'Content here',making it look like readable English.Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text and a search for 'lorem ipsum' will uncover many websites still in their infancy.Various versions have evolved over the years,sometimes by accident,sometimes on purpose(injected humour and the like).",
     workplace: "Bangalore",
     education: "Bachelor degree in any computer course",
     experience: "1 to 2 years",
    },
    { 
     index: 2,
     image: "../images/linkedin.png",
     title: "Business Associate",
     rate:  "₹15000-40000/m",
     av: "Part Time",
     companyName: "Uber",
     location: "India",
     vacancy: "01",
     hours: "25h / week",
     description: "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters,as opposed to using 'Content here',making it look like readable English.Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text and a search for 'lorem ipsum' will uncover many websites still in their infancy.Various versions have evolved over the years,sometimes by accident,sometimes on purpose(injected humour and the like).",
     workplace: "Hyderabad",
     education: "Bachelor degree in any Engineering course",
     experience: "3 to 5 years",
    },
    { 
     index: 3,
     image: "../images/yahoo.png",
     title: "User Experience",
     rate:  "₹15000-40000/m",
     av: "Full Time",
     companyName: "Yahoo",
     location: "India",
     vacancy: "01",
     hours: "25h / week",
     description: "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters,as opposed to using 'Content here',making it look like readable English.Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text and a search for 'lorem ipsum' will uncover many websites still in their infancy.Various versions have evolved over the years,sometimes by accident,sometimes on purpose(injected humour and the like).",
     workplace: "Chennai",
     education: "Bachelor degree in any computer course",
     experience: "6 to 7 years",
    },
    { 
     index: 4,
     image: "../images/instagram.png",
     title: "Web Developer",
     rate:  "₹9000-12000/Project",
     av: "Part Time",
     companyName: "Instagram",
     location: "India",
     vacancy: "04",
     hours: "20h / week",
     description: "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters,as opposed to using 'Content here',making it look like readable English.Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text and a search for 'lorem ipsum' will uncover many websites still in their infancy.Various versions have evolved over the years,sometimes by accident,sometimes on purpose(injected humour and the like).",
     workplace: "Kolkata",
     education: "Bachelor degree in any computer course",
     experience: "1 to 2 years",
    },
];